name: Build Custom Orbot

on:
  workflow_dispatch: # Позволяет запускать сборку одной кнопкой вручную

jobs:
  build:
    runs-on: ubuntu-latest # Собираем на Linux, где нет ошибок Windows NDK

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # Корректно выкачиваем Си-туннели

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android NDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Orbot-Custom-Auto
          path: app/build/outputs/apk/debug/app-debug.apk
